### ISSUE TITLE
(MESA) partner is now both in the network, and not.

### ISSUE THREAD

**Issue by mariopaolucci** [LABSS/PROTON-OC#176]
This should be solved as soon as the https://github.com/LABSS/PROTON-OC/tree/mesa-test-fixing branch is merged.

**Comment by Kubasinska** [comment]
I think it is time to make a decision on this issue. In order to maintain consistency with the other networks, I propose to manage partners in the same way as the other networks are managed.

**Comment by mariopaolucci** [comment]
I'll second that.
