### ISSUE TITLE
The "ask" procedure from Netlogo to Python

### ISSUE THREAD

**Issue by Kubasinska** [LABSS/PROTON-OC#188]
The primitive netlogo `ask agentset` takes agents in random order. Quoting from the [netlogo documentation](http://ccl.northwestern.edu/netlogo/docs/dict/ask.html): "when ask is used with an agentset each agent will take its turn in a random order". In Python translation this pattern must be respected.

**Comment by mariopaolucci** [comment]
That's true. I was counting on `step` to do the randomizing work, but we should also check that agents are shuffled before any important call in the initialization. In other words, we get the shuffling from *mesa* in the step procedure **but** we should probably substitute calls to `schedule.agents` with shuffled calls.

In fact, in the mesa source code, a solution might be using `schedule.agent_buffer(True)`. See
https://github.com/projectmesa/mesa/blob/7c5f12cbc23a423f3f54c91333408e59918e4a2a/mesa/time.py#L89-L100

We should at some point pause development to address this systematically.

**Comment by Kubasinska** [comment]
I will solve this problem as soon as possible.
